version: "3"

networks:
  caddy-network:
    driver: bridge

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8162:8162"
    environment:
      - DOMAIN_NAME=${CADDY_DOMAIN_NAME}
    volumes:
      - $PWD/caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - $PWD/caddy:/data/caddy
      - $PWD/caddy:/config/caddy
    networks:
      - caddy-network

  clashurl:
    image: baoniu/clashurl:latest
    restart: unless-stopped
    environment:
      - APP_KEY=${APP_KEY}
    expose:
      - 8162
    networks:
      - caddy-network

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - METHOD=${SHADOW_SOCKS_METHOD}
      - PASSWORD=${SHADOW_SOCKS_PASSWORD}
    restart: unless-stopped
    networks:
      - caddy-network

#  chatgpt:
#    restart: unless-stopped
#    image: yidadaa/chatgpt-next-web
#    environment:
#      - OPENAI_API_KEY=${CHAT_GPT_OPEN_API_KEY}
#      - CODE=${CHAT_GPT_WEB_PASSWORD}
#    expose:
#      - 3000
#    networks:
#      - caddy-network